config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  devise_for :users

  resources :sessions
  resources :posts do
    member { post :vote }

  end
  resources :posts do
    resources :comments
  end
  post 'posts/:id/comment' => 'posts#comment'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates_presence_of :name, :url, :username
	belongs_to :user
	has_reputation :votes, source: :user, aggregated_by: :sum
	acts_as_commentable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vote.rb
class Vote < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
before_filter :load_commentable
before_filter :get_post

def get_post
  @post = Post.find(params[:post_id])
end

def create
  @comment = @commentable.comments.build(params[:comment])
  @comment.user = current_user
  respond_to do |format|
    if @comment.save
      format.html { redirect_to @commentable }
    else
      format.html { render :action => 'new' }
    end
  end
end
def index
  @commentable = find_commentable
  @comments = @commentable.comments
end

private

def find_commentable
  params.each do |name, value|
    if name =~ /(.+)_id$/
      return $1.classify.constantize.find(value)
    end
  end
  nil
end

def load_commentable
  @commentable = params[:commentable_type].camelize.constantize.find(params[:commentable_id])
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, only: [:vote]

  def vote
    value = params[:type] == "up" ? 1 : -1
    @post = Post.find(params[:id])
    @post.add_or_update_evaluation(:votes, value, current_user)
    redirect_to :back, notice: "Vote Registered."
  end

  def comment
    @post = Post.find(params[:id])
    comment = @post.comments.create
    comment.comment = params[:comment][:comment]
    comment.user_id = current_user.id
    comment.title = current_user.email
    comment.save
    redirect_to :back, notice: "Comment accepted."
  end

  def url_with_protocol(url)
    /^http/.match(url) ? url : "http://#{url}"
  end

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
    @current_user = current_user
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @current_user = current_user
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.url = url_with_protocol(@post.url)
    # If the user is not anonymous, change the username to the logged in user's email.
    if @post.username.blank?
      @post.username = current_user.email
    end
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :url, :username, :votes)
    end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_vote, only: [:show, :edit, :update, :destroy]

  # GET /votes
  # GET /votes.json
  def index
    @votes = Vote.all
  end

  # GET /votes/1
  # GET /votes/1.json
  def show
  end

  # GET /votes/new
  def new
    @vote = Vote.new
  end

  # GET /votes/1/edit
  def edit
  end

  # POST /votes
  # POST /votes.json
  def create
    @vote = Vote.new(vote_params)

    respond_to do |format|
      if @vote.save
        format.html { redirect_to @vote, notice: 'Vote was successfully created.' }
        format.json { render :show, status: :created, location: @vote }
      else
        format.html { render :new }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /votes/1
  # PATCH/PUT /votes/1.json
  def update
    respond_to do |format|
      if @vote.update(vote_params)
        format.html { redirect_to @vote, notice: 'Vote was successfully updated.' }
        format.json { render :show, status: :ok, location: @vote }
      else
        format.html { render :edit }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.json
  def destroy
    @vote.destroy
    respond_to do |format|
      format.html { redirect_to votes_url, notice: 'Vote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote
      @vote = Vote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vote_params
      params.require(:vote).permit(:user_id, :post_id, :is_upvote)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>New Reddit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<div class="container"
<body>
<h1><%= image_tag "/assets/new_reddit.png" %>New Reddit</h1>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

<%= yield %>

</body>
</div>
</html>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Newreddit
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - if notice
      %p.alert.alert-success= notice
    - if alert
      %p.alert.alert-danger= alert
    = yield

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    Post title:
    <%= f.text_field :name, placeholder: "Description of link", class: 'form-control' %>
  </div>
  <div class="field">
    Link URL:
    <%= f.text_field :url, placeholder: "http://example.com", class: 'form-control' %>
  </div>
  <% if !user_signed_in? %>
  <div class="field">
    Username: 
    <%= f.text_field :username, placeholder: "yourname@example.com", class: 'form-control' %>
  </div>
  <% end %> 
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h3>Editing post</h3>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h3>All posts</h3>

<table class="table">
  <thead>
    <tr>
      <th>Score</th>
      <% if user_signed_in? %>
      <th colspan="2">Votes</th>
      <% end %>
      <th>Name</th>
      <th>Link</th>
      <th>Submitted by:</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.reputation_for(:votes).to_i %></td>
        <% if user_signed_in? %>
        <td colspan="2">
          <%= link_to "Upvote", vote_post_path(post, type: "up"), method: "post" %>
          | 
          <%= link_to "Downvote", vote_post_path(post, type: "down"), method: "post" %>
        </td>
        <% end %>
        <td><strong><%= post.name %></strong></td>
        <td><%= link_to post.url, post.url %></td>
        <td><%= post.username %></td>
        <td><%= link_to 'Read Comments', post %></td>
        <% if post.username == @current_user.email %>
          <td><%= link_to 'Edit', edit_post_path(post) %></td>
          <td><%= link_to 'Delete Post', post, method: :delete, data: { confirm: 'Are you sure you want to delete this post?' } %></td>
        <% else %>
          <td colspan="2">
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h3>New post</h3>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<h1>
  <%= @post.name %>
</h1>

<p>
  <strong>Link:</strong>
  <%= link_to @post.url, @post.url %>
</p>

<p>
  <strong>Submitted by</strong>
  <%= @post.username %>
</p>

<p>
  <strong>Score:</strong>
  <%= @post.reputation_for(:votes).to_i %>
</p>
<% if @post.username == @current_user.email %>
<%= link_to 'Edit', edit_post_path(@post) %> |
<% end %>
<%= link_to 'Return to front page', posts_path %>
<h3>Comments</h3>

<table class="table">
<% for comment in @post.comments %>
	<tr>
  	<td><i><%= comment.title %> on <%= comment.created_at.strftime("%B %d, %Y") %>:</i><p><%= simple_format comment.comment %></p></td>
  </tr>
<% end %>
</table>

<h3>New Comment</h3>

<%= form_tag controller: "posts", action: "comment", id: @post.id %>
  <%= text_area "comment", "comment", :rows => 5, :cols => 50 %> <br />
  <%= submit_tag "Submit Comment" %>
</form>

app/views/votes/_form.html.erb
<%= form_for(@vote) do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% @vote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :is_upvote %><br>
    <%= f.check_box :is_upvote %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/votes/edit.html.erb
<h1>Editing vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<h1>Listing votes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Post</th>
      <th>Is upvote</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @votes.each do |vote| %>
      <tr>
        <td><%= vote.user_id %></td>
        <td><%= vote.post_id %></td>
        <td><%= vote.is_upvote %></td>
        <td><%= link_to 'Show', vote %></td>
        <td><%= link_to 'Edit', edit_vote_path(vote) %></td>
        <td><%= link_to 'Destroy', vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vote', new_vote_path %>

app/views/votes/new.html.erb
<h1>New vote</h1>

<%= render 'form' %>

<%= link_to 'Back', votes_path %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @vote.user_id %>
</p>

<p>
  <strong>Post:</strong>
  <%= @vote.post_id %>
</p>

<p>
  <strong>Is upvote:</strong>
  <%= @vote.is_upvote %>
</p>

<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>